include:
  - docker-compose.observability.yml

services:
  mars-probe-simulator-app:
    build:
      context: ..
      dockerfile: docker/prod/Dockerfile
    restart: always

  mars-probe-simulator-db:
    restart: always
