"""init

Revision ID: 57392c464b34
Revises: 
Create Date: 2026-05-31 01:26:45.014023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57392c464b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', name='direction'), nullable=False),
    sa.CheckConstraint('x >= 0', name='check_valid_probe_x_position'),
    sa.CheckConstraint('y >= 0', name='check_valid_probe_y_position'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grid',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('probe_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('x >= 0', name='check_valid_grid_x_position'),
    sa.CheckConstraint('y >= 0', name='check_valid_grid_y_position'),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('probe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid')
    op.drop_table('probe')
    op.execute("DROP TYPE IF EXISTS direction")
    # ### end Alembic commands ###
